/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
library;

// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'package:flutter/material.dart';
import '../atomic/atomic.dart';

part 'color/wds_semantic_color_backgroud.dart';
part 'color/wds_semantic_color_border.dart';
part 'color/wds_semantic_color_material.dart';
part 'color/wds_semantic_color_status.dart';
part 'color/wds_semantic_color_text.dart';

const Color $cta = WdsAtomicColorNeutral.v900;
const Color $primary = WdsAtomicColorBlue.v400;
const Color $secondary = WdsAtomicColorPink.v500;
