/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
library;

// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'package:flutter/material.dart';
import '../atomic/atomic.dart';

part 'shadow/wds_semantic_shadow_cool_neutral.dart';
part 'shadow/wds_semantic_shadow_neutral.dart';
