name: wds_flutter
packages:
  - packages/**
  - tools/**
ide:
  intellij: false
  vscode:
    useWorkspaces: true
scripts:
  # Install: flutter pub get
  install:
    description: "Install all the dependencies"
    run: flutter pub get && melos exec -c 2 -- "flutter pub get"

  # Build: Widgetbook
  build-widgetbook:
    description: "Build Widgetbook"
    run: cd packages/widgetbook && fvm exec dart run build_runner build --delete-conflicting-outputs && cd ../..

  # Format: All
  format:
    description: "Format all the files"
    run: fvm exec melos exec -c 2 -- "dart fix --apply && dart format ."
