/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
part of '../wds_semantic_shadow.dart';

class WdsSemanticShadowNeutral {
  const WdsSemanticShadowNeutral._();
  static const List<BoxShadow> emphasize = [
    BoxShadow(
      offset: Offset(0, WdsAtomicOffsetY.sm),
      blurRadius: WdsAtomicBlur.lg,
      color: Color(0x1F000000),
    ),
    BoxShadow(
      offset: Offset(0, WdsAtomicOffsetY.xs),
      blurRadius: WdsAtomicBlur.md,
      color: Color(0x14000000),
    ),
    BoxShadow(blurRadius: WdsAtomicBlur.xs, color: Color(0x14000000)),
  ];
  static const List<BoxShadow> heavy = [
    BoxShadow(
      offset: Offset(0, WdsAtomicOffsetY.xxl),
      blurRadius: WdsAtomicBlur.full,
      color: Color(0x1F000000),
    ),
    BoxShadow(
      offset: Offset(0, WdsAtomicOffsetY.xl),
      blurRadius: WdsAtomicBlur.xxl,
      color: Color(0x14000000),
    ),
    BoxShadow(blurRadius: WdsAtomicBlur.lg, color: Color(0x14000000)),
  ];
  static const List<BoxShadow> normal = [
    BoxShadow(
      offset: Offset(0, WdsAtomicOffsetY.xs),
      blurRadius: WdsAtomicBlur.sm,
      color: Color(0x1F000000),
    ),
    BoxShadow(blurRadius: WdsAtomicBlur.xs, color: Color(0x14000000)),
    BoxShadow(blurRadius: WdsAtomicBlur.xs, color: Color(0x14000000)),
  ];
  static const List<BoxShadow> strong = [
    BoxShadow(
      offset: Offset(0, WdsAtomicOffsetY.lg),
      blurRadius: WdsAtomicBlur.xl,
      color: Color(0x1F000000),
    ),
    BoxShadow(
      offset: Offset(0, WdsAtomicOffsetY.md),
      blurRadius: WdsAtomicBlur.lg,
      color: Color(0x14000000),
    ),
    BoxShadow(blurRadius: WdsAtomicBlur.md, color: Color(0x14000000)),
  ];
}
