/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
part of '../wds_semantic_shadow.dart';

class WdsSemanticShadowCoolNeutral {
  const WdsSemanticShadowCoolNeutral._();
  static const List<BoxShadow> emphasize = [
    BoxShadow(
      offset: Offset(0, WdsAtomicOffsetY.v2),
      blurRadius: WdsAtomicBlur.v8,
      color: Color(0x1F819BFF),
    ),
    BoxShadow(
      offset: Offset(0, WdsAtomicOffsetY.v1),
      blurRadius: WdsAtomicBlur.v4,
      color: Color(0x14819BFF),
    ),
    BoxShadow(blurRadius: WdsAtomicBlur.v1, color: Color(0x14819BFF)),
  ];
  static const List<BoxShadow> heavy = [
    BoxShadow(
      offset: Offset(0, WdsAtomicOffsetY.v16),
      blurRadius: WdsAtomicBlur.v20,
      color: Color(0x1F819BFF),
    ),
    BoxShadow(
      offset: Offset(0, WdsAtomicOffsetY.v8),
      blurRadius: WdsAtomicBlur.v16,
      color: Color(0x14819BFF),
    ),
    BoxShadow(blurRadius: WdsAtomicBlur.v8, color: Color(0x14819BFF)),
  ];
  static const List<BoxShadow> normal = [
    BoxShadow(
      offset: Offset(0, WdsAtomicOffsetY.v2),
      blurRadius: WdsAtomicBlur.v12,
      color: Color(0x1F819BFF),
    ),
    BoxShadow(blurRadius: WdsAtomicBlur.v1, color: Color(0x14819BFF)),
  ];
  static const List<BoxShadow> strong = [
    BoxShadow(
      offset: Offset(0, WdsAtomicOffsetY.v6),
      blurRadius: WdsAtomicBlur.v12,
      color: Color(0x1F819BFF),
    ),
    BoxShadow(
      offset: Offset(0, WdsAtomicOffsetY.v4),
      blurRadius: WdsAtomicBlur.v8,
      color: Color(0x14819BFF),
    ),
    BoxShadow(blurRadius: WdsAtomicBlur.v4, color: Color(0x14819BFF)),
  ];
}
