/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
part of '../wds_atomic_color.dart';

class WdsAtomicColorSky {
  const WdsAtomicColorSky._();
  static const Color v50 = Color(0xFFE0F0FF);
  static const Color v100 = Color(0xFFB9DDFF);
  static const Color v200 = Color(0xFF8BC7FF);
  static const Color v300 = Color(0xFF5EB0FE);
  static const Color v400 = Color(0xFF4899E5);
  static const Color v500 = Color(0xFF0084FF);
  static const Color v600 = Color(0xFF0069CA);
  static const Color v700 = Color(0xFF0057A9);
  static const Color v800 = Color(0xFF003E78);
  static const Color v900 = Color(0xFF0A2742);
}
