/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
part of '../wds_atomic_color.dart';

class WdsAtomicColorOrange {
  const WdsAtomicColorOrange._();
  static const Color v50 = Color(0xFFFFE2E0);
  static const Color v100 = Color(0xFFFFBEBA);
  static const Color v200 = Color(0xFFFFA8A3);
  static const Color v300 = Color(0xFFFF8C84);
  static const Color v400 = Color(0xFFF27870);
  static const Color v500 = Color(0xFFF6685F);
  static const Color v600 = Color(0xFFE44E45);
  static const Color v700 = Color(0xFFC6332A);
  static const Color v800 = Color(0xFF94130B);
  static const Color v900 = Color(0xFF700700);
}
