/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
part of '../wds_atomic_color.dart';

class WdsAtomicColorCoolNeutral {
  const WdsAtomicColorCoolNeutral._();
  static const Color v50 = Color(0xFFF8F9FB);
  static const Color v100 = Color(0xFFEAECF0);
  static const Color v200 = Color(0xFFD8DBE2);
  static const Color v300 = Color(0xFFC6C9D0);
  static const Color v400 = Color(0xFFACB1BB);
  static const Color v500 = Color(0xFF838A9A);
  static const Color v600 = Color(0xFF586276);
  static const Color v700 = Color(0xFF455065);
  static const Color v800 = Color(0xFF313B4D);
  static const Color v900 = Color(0xFF1A1F29);
}
