/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
part of '../wds_atomic_color.dart';

class WdsAtomicColorYellow {
  const WdsAtomicColorYellow._();
  static const Color v50 = Color(0xFFFFF4D7);
  static const Color v100 = Color(0xFFFFE7AA);
  static const Color v200 = Color(0xFFFFDE8A);
  static const Color v300 = Color(0xFFFFD566);
  static const Color v400 = Color(0xFFFFCB43);
  static const Color v500 = Color(0xFFFFC120);
  static const Color v600 = Color(0xFFF0AD00);
  static const Color v700 = Color(0xFFBB8700);
  static const Color v800 = Color(0xFF7C5900);
  static const Color v900 = Color(0xFF3E2C00);
}
