/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
library;

// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'package:flutter/material.dart';

part 'color/wds_color_blue.dart';
part 'color/wds_color_brand.dart';
part 'color/wds_color_cool_neutral.dart';
part 'color/wds_color_neutral.dart';
part 'color/wds_color_orange.dart';
part 'color/wds_color_pink.dart';
part 'color/wds_color_sky.dart';
part 'color/wds_color_yellow.dart';

const Color $black = Color(0xFF000000);
const Color $white = Color(0xFFFFFFFF);
