/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
library;

class WdsAtomicRadius {
  const WdsAtomicRadius._();
  static const double v0 = 0;
  static const double v12 = 12;
  static const double v16 = 16;
  static const double v20 = 20;
  static const double v30 = 30;
  static const double v4 = 4;
  static const double v8 = 8;
  static const double v9999 = 9999;
}
