/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
library;

class WdsAtomicBlur {
  const WdsAtomicBlur._();
  static const double full = 20;
  static const double lg = 8;
  static const double md = 4;
  static const double sm = 2;
  static const double xl = 12;
  static const double xs = 1;
  static const double xxl = 16;
}
