/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
library;

class WdsAtomicRadius {
  const WdsAtomicRadius._();
  static const double full = 9999;
  static const double lg = 16;
  static const double md = 12;
  static const double none = 0;
  static const double sm = 8;
  static const double xl = 20;
  static const double xs = 4;
  static const double xxl = 30;
}
