/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
library;

// ignore_for_file: constant_identifier_names, non_constant_identifier_names
import 'package:flutter/material.dart';

part 'wds_atomic_font/wds_atomic_font_family.dart';
part 'wds_atomic_font/wds_atomic_font_line_height.dart';
part 'wds_atomic_font/wds_atomic_font_size.dart';
part 'wds_atomic_font/wds_atomic_font_weight.dart';
