/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
library;

class WdsAtomicOffsetY {
  const WdsAtomicOffsetY._();
  static const double v1 = 1;
  static const double v16 = 16;
  static const double v2 = 2;
  static const double v4 = 4;
  static const double v6 = 6;
  static const double v8 = 8;
}
