/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
library;

class WdsAtomicSpace {
  const WdsAtomicSpace._();
  static const double v0 = 0;
  static const double v1 = 1;
  static const double v12 = 12;
  static const double v16 = 16;
  static const double v2 = 2;
  static const double v20 = 20;
  static const double v24 = 24;
  static const double v32 = 32;
  static const double v4 = 4;
  static const double v40 = 40;
  static const double v48 = 48;
  static const double v6 = 6;
  static const double v64 = 64;
  static const double v8 = 8;
}
