/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
library;

class WdsAtomicSpace {
  const WdsAtomicSpace._();
  static const double md = 4;
  static const double md10 = 48;
  static const double md11 = 64;
  static const double md2 = 6;
  static const double md3 = 8;
  static const double md4 = 12;
  static const double md5 = 16;
  static const double md6 = 20;
  static const double md7 = 24;
  static const double md8 = 32;
  static const double md9 = 40;
  static const double none = 0;
  static const double xs = 2;
  static const double xxs = 1;
}
