/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
library;

class WdsAtomicOffsetY {
  const WdsAtomicOffsetY._();
  static const double lg = 6;
  static const double md = 4;
  static const double sm = 2;
  static const double xl = 8;
  static const double xs = 1;
  static const double xxl = 16;
}
