/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
part of '../font.dart';

class WdsFontWeight {
  const WdsFontWeight._();
  static const FontWeight bold = FontWeight.w600;
  static const FontWeight extraBold = FontWeight.w800;
  static const FontWeight medium = FontWeight.w500;
  static const FontWeight regular = FontWeight.w400;
}
