/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
part of '../font.dart';

class WdsFontSize {
  const WdsFontSize._();
  static const double v10 = 10;
  static const double v11 = 11;
  static const double v12 = 12;
  static const double v13 = 13;
  static const double v14 = 14;
  static const double v15 = 15;
  static const double v16 = 16;
  static const double v17 = 17;
  static const double v18 = 18;
  static const double v20 = 20;
  static const double v22 = 22;
  static const double v32 = 32;
}
