/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
part of '../font.dart';

class WdsFontFamily {
  const WdsFontFamily._();
  static const String pretendard = 'Pretendard';
}
