/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
part of '../wds_atomic_font.dart';

class WdsAtomicFontWeight {
  const WdsAtomicFontWeight._();
  static const FontWeight v400 = FontWeight.w400;
  static const FontWeight v500 = FontWeight.w500;
  static const FontWeight v600 = FontWeight.w600;
  static const FontWeight v800 = FontWeight.w800;
}
