/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
part of '../color.dart';

class WdsSemanticColorMaterial {
  const WdsSemanticColorMaterial._();
  static const Color dimmer = Color(0x99000000);
  static const Color pressed = Color(0x1A000000);
}
