/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
part of '../wds_semantic_color.dart';

class WdsSemanticColorText {
  const WdsSemanticColorText._();
  static const Color alternative = WdsAtomicColorNeutral.v500;
  static const Color assistive = WdsAtomicColorNeutral.v400;
  static const Color disable = WdsAtomicColorNeutral.v100;
  static const Color neutral = WdsAtomicColorNeutral.v600;
  static const Color normal = WdsAtomicColorNeutral.v900;
  static const Color strong = $black;
}
