/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
part of '../wds_semantic_color.dart';

class WdsSemanticColorBackgroud {
  const WdsSemanticColorBackgroud._();
  static const Color alternative = WdsAtomicColorCoolNeutral.v50;
  static const Color normal = $white;
}
