/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
part of '../color.dart';

class WdsSemanticColorStatus {
  const WdsSemanticColorStatus._();
  static const Color cautionaty = WdsColorOrange.v500;
  static const Color destructive = WdsColorOrange.v600;
  static const Color positive = WdsColorBlue.v400;
}
