/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
part of '../color.dart';

class WdsColorBrand {
  const WdsColorBrand._();
  static const Color chuu = Color(0xFFEB7993);
  static const Color gemhour = Color(0xFF611161);
  static const Color hapakristin = Color(0xFFE83983);
}
