/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
// ignore_for_file: constant_identifier_names, non_constant_identifier_names
part of '../color.dart';

class WdsColorBlue {
  const WdsColorBlue._();
  static const Color v50 = Color(0xFFE6EBFD);
  static const Color v100 = Color(0xFFCDD8FF);
  static const Color v200 = Color(0xFFA3B6FF);
  static const Color v300 = Color(0xFF819BFF);
  static const Color v400 = Color(0xFF5B7BF3);
  static const Color v500 = Color(0xFF325AF0);
  static const Color v600 = Color(0xFF254CDF);
  static const Color v700 = Color(0xFF1C3EC0);
  static const Color v800 = Color(0xFF0A2BA9);
  static const Color v900 = Color(0xFF092178);
}
