/// 🤖 GENERATED BY token_generator
///
/// maintained by [seunghwanly](github.com/seunghwanly)
library;
// ignore_for_file: constant_identifier_names, non_constant_identifier_names

import 'package:flutter/material.dart';
import 'package:wds_tokens/wds_tokens.dart' as t;

/// WDS 컬러 시스템 통합 인터페이스
///
/// Components에서는 이 클래스를 통해서만 색상에 접근해야 합니다.
class WdsColors {
  const WdsColors._();

  static const Color white = t.$white;
  static const Color black = t.$black;

  static const Color blue50 = t.WdsColorBlue.v50;
  static const Color blue100 = t.WdsColorBlue.v100;
  static const Color blue200 = t.WdsColorBlue.v200;
  static const Color blue300 = t.WdsColorBlue.v300;
  static const Color blue400 = t.WdsColorBlue.v400;
  static const Color blue500 = t.WdsColorBlue.v500;
  static const Color blue600 = t.WdsColorBlue.v600;
  static const Color blue700 = t.WdsColorBlue.v700;
  static const Color blue800 = t.WdsColorBlue.v800;
  static const Color blue900 = t.WdsColorBlue.v900;

  static const Color neutral50 = t.WdsColorNeutral.v50;
  static const Color neutral100 = t.WdsColorNeutral.v100;
  static const Color neutral200 = t.WdsColorNeutral.v200;
  static const Color neutral300 = t.WdsColorNeutral.v300;
  static const Color neutral400 = t.WdsColorNeutral.v400;
  static const Color neutral500 = t.WdsColorNeutral.v500;
  static const Color neutral600 = t.WdsColorNeutral.v600;
  static const Color neutral700 = t.WdsColorNeutral.v700;
  static const Color neutral800 = t.WdsColorNeutral.v800;
  static const Color neutral900 = t.WdsColorNeutral.v900;

  static const Color coolNeutral50 = t.WdsColorCoolNeutral.v50;
  static const Color coolNeutral100 = t.WdsColorCoolNeutral.v100;
  static const Color coolNeutral200 = t.WdsColorCoolNeutral.v200;
  static const Color coolNeutral300 = t.WdsColorCoolNeutral.v300;
  static const Color coolNeutral400 = t.WdsColorCoolNeutral.v400;
  static const Color coolNeutral500 = t.WdsColorCoolNeutral.v500;
  static const Color coolNeutral600 = t.WdsColorCoolNeutral.v600;
  static const Color coolNeutral700 = t.WdsColorCoolNeutral.v700;
  static const Color coolNeutral800 = t.WdsColorCoolNeutral.v800;
  static const Color coolNeutral900 = t.WdsColorCoolNeutral.v900;

  static const Color orange50 = t.WdsColorOrange.v50;
  static const Color orange100 = t.WdsColorOrange.v100;
  static const Color orange200 = t.WdsColorOrange.v200;
  static const Color orange300 = t.WdsColorOrange.v300;
  static const Color orange400 = t.WdsColorOrange.v400;
  static const Color orange500 = t.WdsColorOrange.v500;
  static const Color orange600 = t.WdsColorOrange.v600;
  static const Color orange700 = t.WdsColorOrange.v700;
  static const Color orange800 = t.WdsColorOrange.v800;
  static const Color orange900 = t.WdsColorOrange.v900;

  static const Color pink50 = t.WdsColorPink.v50;
  static const Color pink100 = t.WdsColorPink.v100;
  static const Color pink200 = t.WdsColorPink.v200;
  static const Color pink300 = t.WdsColorPink.v300;
  static const Color pink400 = t.WdsColorPink.v400;
  static const Color pink500 = t.WdsColorPink.v500;
  static const Color pink600 = t.WdsColorPink.v600;
  static const Color pink700 = t.WdsColorPink.v700;
  static const Color pink800 = t.WdsColorPink.v800;
  static const Color pink900 = t.WdsColorPink.v900;

  static const Color sky50 = t.WdsColorSky.v50;
  static const Color sky100 = t.WdsColorSky.v100;
  static const Color sky200 = t.WdsColorSky.v200;
  static const Color sky300 = t.WdsColorSky.v300;
  static const Color sky400 = t.WdsColorSky.v400;
  static const Color sky500 = t.WdsColorSky.v500;
  static const Color sky600 = t.WdsColorSky.v600;
  static const Color sky700 = t.WdsColorSky.v700;
  static const Color sky800 = t.WdsColorSky.v800;
  static const Color sky900 = t.WdsColorSky.v900;

  static const Color yellow50 = t.WdsColorYellow.v50;
  static const Color yellow100 = t.WdsColorYellow.v100;
  static const Color yellow200 = t.WdsColorYellow.v200;
  static const Color yellow300 = t.WdsColorYellow.v300;
  static const Color yellow400 = t.WdsColorYellow.v400;
  static const Color yellow500 = t.WdsColorYellow.v500;
  static const Color yellow600 = t.WdsColorYellow.v600;
  static const Color yellow700 = t.WdsColorYellow.v700;
  static const Color yellow800 = t.WdsColorYellow.v800;
  static const Color yellow900 = t.WdsColorYellow.v900;

  static const Color chuu = t.WdsColorBrand.chuu;
  static const Color hapakristin = t.WdsColorBrand.hapakristin;
  static const Color gemhour = t.WdsColorBrand.gemhour;

  static const Color cta = t.$cta;
  static const Color primary = t.$primary;
  static const Color secondary = t.$secondary;

  static const Color backgroundAlternative =
      t.WdsSemanticColorBackgroud.alternative;
  static const Color backgroundNormal = t.WdsSemanticColorBackgroud.normal;

  static const Color borderAlternative = t.WdsSemanticColorBorder.alternative;
  static const Color borderNeutral = t.WdsSemanticColorBorder.neutral;

  static const Color materialDimmer = t.WdsSemanticColorMaterial.dimmer;
  static const Color materialPressed = t.WdsSemanticColorMaterial.pressed;

  static const Color statusCautionaty = t.WdsSemanticColorStatus.cautionaty;
  static const Color statusDestructive = t.WdsSemanticColorStatus.destructive;
  static const Color statusPositive = t.WdsSemanticColorStatus.positive;

  static const Color textAlternative = t.WdsSemanticColorText.alternative;
  static const Color textAssistive = t.WdsSemanticColorText.assistive;
  static const Color textDisable = t.WdsSemanticColorText.disable;
  static const Color textNeutral = t.WdsSemanticColorText.neutral;
  static const Color textNormal = t.WdsSemanticColorText.normal;
  static const Color textStrong = t.WdsSemanticColorText.strong;
}
